### PR TITLE
Charlie current limiter 2

### LINKED ISSUE #13: Prototyping: Current Limiting on Drivetrain
-take an existing robot and apply current limiting profiles to the drivetrain
-goal is to shut down the motors if they're stalling for too long (pushing against opponent) (or apply motor brake?)
-but do not prevent ability to fight back minor skirmishes or recover from crashing into a field obstacle
-add a warning system before motors cut off so that drive team does not get surprised by a sudden power loss?

### PR DESCRIPTION
**Pull request by Citysurvivor**
Removed duplicate robotContainer initializer (return it to the way it was). Optimized calculations for current limiter driver feedback.

### CODE REVIEW

File: src/main/java/frc/robot/RobotContainer.java [hunk 1]
```diff
@@ -35,30 +35,27 @@
...
-  private final double AUTO_DRIVE_TIME = 1.0;
-  private final double AUTO_LEFT_MOTOR_SPEED = 0.2;
-  private final double AUTO_RIGHT_MOTOR_SPEED = 0.2;
+    private Command moveArm;
+    private Command rampShooterCommand;
+    private Command incrementFeeder;
+    private Logger logger = Logger.getLogger("RobotContainer");
+    private final double AUTO_DRIVE_TIME = 1.0;
+    private final double AUTO_LEFT_MOTOR_SPEED = 0.2;
+    private final double AUTO_RIGHT_MOTOR_SPEED = 0.2;
```
Comment (Citysurvivor) [inline src/main/java/frc/robot/RobotContainer.java:58]: Just fixed the tab spacing here (from 2 spaces to our standard of 4 spaces)

File: src/main/java/frc/robot/RobotContainer.java [hunk 2]
```diff
@@ -140,24 +137,8 @@ else if (selectorOne == 1 || selectorTwo == 1) {
...
-    /**
-     * Initialize the current RobotContainer instance
-     */
-    public static void init() {
-        if (currentInstance == null) {
-            currentInstance = new RobotContainer();
-        }
-    }
-
-    public static RobotContainer getInstance() {
```
Comment (Citysurvivor) [inline src/main/java/frc/robot/RobotContainer.java:157]: This code that I added in [pull request #124](https://github.com/FRC2706/2020-2706-Robot-Code/pull/124) was not needed. RobotContainer is public.

**Review by nicojopr — APPROVED** [review]
In the working world it would be recommended to separate out the revert from the next improvements being delivered. Avoid bundling too many independent changes in one pull request.
